/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const ProyectosIndexLazyImport = createFileRoute('/proyectos/')()
const NosotrosIndexLazyImport = createFileRoute('/nosotros/')()
const ComplianceIndexLazyImport = createFileRoute('/compliance/')()
const ChiquitaniaIndexLazyImport = createFileRoute('/chiquitania/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProyectosIndexLazyRoute = ProyectosIndexLazyImport.update({
  path: '/proyectos/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/proyectos/index.lazy').then((d) => d.Route),
)

const NosotrosIndexLazyRoute = NosotrosIndexLazyImport.update({
  path: '/nosotros/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/nosotros/index.lazy').then((d) => d.Route),
)

const ComplianceIndexLazyRoute = ComplianceIndexLazyImport.update({
  path: '/compliance/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/compliance/index.lazy').then((d) => d.Route),
)

const ChiquitaniaIndexLazyRoute = ChiquitaniaIndexLazyImport.update({
  path: '/chiquitania/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/chiquitania/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/chiquitania/': {
      id: '/chiquitania/'
      path: '/chiquitania'
      fullPath: '/chiquitania'
      preLoaderRoute: typeof ChiquitaniaIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/compliance/': {
      id: '/compliance/'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/nosotros/': {
      id: '/nosotros/'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  ChiquitaniaIndexLazyRoute,
  ComplianceIndexLazyRoute,
  NosotrosIndexLazyRoute,
  ProyectosIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/chiquitania/",
        "/compliance/",
        "/nosotros/",
        "/proyectos/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/chiquitania/": {
      "filePath": "chiquitania/index.lazy.tsx"
    },
    "/compliance/": {
      "filePath": "compliance/index.lazy.tsx"
    },
    "/nosotros/": {
      "filePath": "nosotros/index.lazy.tsx"
    },
    "/proyectos/": {
      "filePath": "proyectos/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
